name: xmpp_stone_example
description: Demonstrates how to use the xmpp_stone plugin.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xmpp_stone:
    path: ../
  cupertino_icons: ^1.0.0
  decorated_flutter: ^0.23.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true